apiVersion: v1
kind: Service
metadata:
  name: sukt-core-auth-service
  namespace: sukt-core
spec:
  type: NodePort
  selector:
    app: sukt-core-auth-pod
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30101
